# coding: utf-8

"""
    Suada API

    OpenAPI specification for the Suada API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.completion import Completion

class TestCompletion(unittest.TestCase):
    """Completion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Completion:
        """Test Completion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Completion`
        """
        model = Completion()
        if include_optional:
            return Completion(
                model = 'suada-v1',
                messages = [{"role":"system","content":"You are a helpful assistant."},{"role":"user","content":"Hello!"}],
                temperature = 1.337,
                top_p = 1.337,
                frequency_penalty = 1.337,
                presence_penalty = 1.337,
                stop = [
                    ''
                    ],
                max_tokens = 1.337,
                n = 1.337,
                stream = True
            )
        else:
            return Completion(
                model = 'suada-v1',
                messages = [{"role":"system","content":"You are a helpful assistant."},{"role":"user","content":"Hello!"}],
        )
        """

    def testCompletion(self):
        """Test Completion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
