# coding: utf-8

"""
    Suada API

    OpenAPI specification for the Suada API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.completion_messages_inner import CompletionMessagesInner

class TestCompletionMessagesInner(unittest.TestCase):
    """CompletionMessagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompletionMessagesInner:
        """Test CompletionMessagesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompletionMessagesInner`
        """
        model = CompletionMessagesInner()
        if include_optional:
            return CompletionMessagesInner(
                role = 'system',
                content = '',
                name = ''
            )
        else:
            return CompletionMessagesInner(
        )
        """

    def testCompletionMessagesInner(self):
        """Test CompletionMessagesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
