# coding: utf-8

"""
    Suada API

    OpenAPI specification for the Suada API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "suada-client"
VERSION = "1.0.0-rc1"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Suada API",
    author="Suada",
    author_email="hello@suada.ai",
    url="https://suada.ai",
    keywords=["NSFW AI", "AI", "Suada API", "Artificial Intelligence", "NSFW"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="",
    package_data={"suada_client": ["py.typed"]},
)